/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMenuItem: typeof import('./src/components/menu/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/components/menu/AppSidebar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Dataview: typeof import('./src/components/Dataview.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/menu/SidebarMenu.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
